package com.kunal.universalvideo

import android.app.Activity
import android.content.ContentValues
import android.content.Intent
import android.content.pm.PackageManager
import android.media.MediaCodec
import android.media.MediaExtractor
import android.media.MediaFormat
import android.media.MediaMuxer
import android.media.projection.MediaProjectionManager
import android.os.Bundle
import android.os.Handler
import android.provider.MediaStore
import android.provider.Settings
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import android.view.accessibility.AccessibilityNodeInfo
import android.widget.*
import java.io.File
import java.io.FileInputStream
import java.util.Locale
import java.util.UUID

/** Production 1..13 workflow controller. Each stage has a real prerequisite and persisted evidence. */
class MainActivity : androidx.activity.ComponentActivity() {
    companion object {
        const val PREFS = "kuv"; const val TARGET = "target_package"; const val SESSION = "session_id"
        const val STORY = "story"; const val PLAN = "plan"; const val SCENES = "scenes"; const val AUDIO = "audio_file"
        const val RECORDING = "recording_uri"; const val FINAL = "final_uri"; const val RECORDING_START = "recording_start"
    }
    private lateinit var gate: StageGate; private lateinit var status: TextView; private lateinit var story: EditText; private lateinit var targetSpinner: Spinner
    private var bridge: LocalBridgeService? = null; private var target=""; private var sid=""; private var tts: TextToSpeech?=null
    private var apps: List<android.content.pm.ApplicationInfo> = emptyList(); private val mainHandler=Handler(mainLooper)
    private val capture=registerForActivityResult(androidx.activity.result.contract.ActivityResultContracts.StartActivityForResult()){r->
        if(r.resultCode==Activity.RESULT_OK&&r.data!=null){val i=Intent(this,ScreenCaptureService::class.java).setAction(ScreenCaptureService.START).putExtra(ScreenCaptureService.CODE,r.resultCode).putExtra(ScreenCaptureService.DATA,r.data);if(android.os.Build.VERSION.SDK_INT>=26)startForegroundService(i)else startService(i);status.text="Stage 10 RUNNING • recording started"}else fail(10,"Screen-recording permission cancelled")}
    override fun onCreate(b:Bundle?){super.onCreate(b);gate=StageGate(this);val p=getSharedPreferences(PREFS,MODE_PRIVATE);sid=p.getString(SESSION,null)?:UUID.randomUUID().toString();p.edit().putString(SESSION,sid).apply();buildUi(p);bridge=LocalBridgeService(this,sid){m->runOnUiThread{status.text=m}};bridge?.start();stage1()}
    private fun buildUi(p:android.content.SharedPreferences){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,24,24,24)};root.addView(TextView(this).apply{text="Kunal Universal Video • 13 Stage Engine";textSize=25f});status=TextView(this).apply{textSize=15f;setPadding(0,12,0,12)};root.addView(status);targetSpinner=Spinner(this);root.addView(targetSpinner);story=EditText(this).apply{hint="5 • Enter story";minLines=4;setText(p.getString(STORY,""))};root.addView(story,LinearLayout.LayoutParams(-1,180));val actions=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};fun button(t:String,c:()->Unit)=Button(this).apply{text=t;setOnClickListener{c()};actions.addView(this)};button("1 • START / DIAGNOSTIC"){stage1()};button("2 • ENABLE ACCESSIBILITY / CONNECT"){connectMobile()};button("3 • SELECT / SAVE TARGET"){selectTarget()};button("4 • STUDY SELECTED APK"){studyTarget()};button("5 • SAVE STORY INPUT"){saveStory()};button("6 • OPERATE SELECTED TARGET"){operateTarget()};button("7 • DEEP TARGET UNDERSTANDING"){deepStudy()};button("8 • CREATE EXACT SCENE PLAN"){scenePlan()};button("9 • BUILD PRODUCTION PLAN / PROMPTS"){buildPlan()};button("10 • CREATE AUDIO / VOICE / MUSIC / SFX + RECORD"){audioAndRecord()};button("11 • ASSEMBLE / EDIT"){assembleEdit()};button("12 • VERIFY / AUTO-FIX"){verifyAndFix()};button("13 • FINAL GALLERY EXPORT"){finalExport()};button("REFRESH STATUS"){renderStatus()};val scroll=ScrollView(this);scroll.isFillViewport=true;scroll.addView(actions);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));setContentView(root)}
    private fun begin(id:Int)=if(!gate.isUnlocked(id)||!gate.begin(id)){status.text="Stage $id LOCKED or already active";false}else true
    private fun pass(id:Int,e:String){if(gate.pass(id,e)){status.text="Stage $id PASS • $e";renderStatus()}else status.text="Stage $id PASS REJECTED by gate"}
    private fun fail(id:Int,e:String){gate.fail(id,e);status.text="Stage $id FAIL • $e";renderStatus()}
    private fun prefs()=getSharedPreferences(PREFS,MODE_PRIVATE)
    private fun stage1(){if(gate.state(1)!=StageGate.State.PASS){gate.resetForRepair(1);if(gate.begin(1))gate.pass(1,"MainActivity launched; workflow controller attached")};loadApps();renderStatus()}
    private fun renderStatus(){if(!::gate.isInitialized)return;val id=gate.currentStage();val st=gate.state(id);status.text="Stage $id • ${st.name} • ${gate.evidenceJson().optBoolean("final_pass")}\nSession ${sid.take(8)}"}
    private fun loadApps(){apps=packageManager.getInstalledApplications(PackageManager.ApplicationInfoFlags.of(0)).filter{it.packageName!=packageName}.sortedBy{packageManager.getApplicationLabel(it).toString().lowercase()};targetSpinner.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,apps.map{"${packageManager.getApplicationLabel(it)}\n${it.packageName}"});val saved=prefs().getString(TARGET,"")?:"";val idx=apps.indexOfFirst{it.packageName==saved};if(idx>=0)targetSpinner.setSelection(idx)}
    private fun openAccessibility(){startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))}
    private fun connectMobile(){if(!begin(2))return;if(!UniversalAccessibilityService.isEnabled){fail(2,"Accessibility service is not enabled");openAccessibility();return};pass(2,"Accessibility enabled and local controller session ready")}
    private fun selectTarget(){if(!begin(3))return;val pos=targetSpinner.selectedItemPosition;if(pos !in apps.indices){fail(3,"No target selected");return};target=apps[pos].packageName;prefs().edit().putString(TARGET,target).apply();UniversalAccessibilityService.targetPackage=target;bridge?.connect(target);pass(3,"Target package selected and local controller session connected: $target")}
    private fun studyTarget(){if(!begin(4))return;val ai=try{packageManager.getApplicationInfo(target,0)}catch(_:Exception){null};if(ai==null){fail(4,"Target package not installed");return};if(packageManager.getLaunchIntentForPackage(target)==null){fail(4,"Target has no launch activity");return};pass(4,"Target manifest/package validated and launch activity exists")}
    private fun saveStory(){if(!begin(5))return;val s=story.text.toString().trim();if(s.length<10){fail(5,"Story must contain at least 10 characters");return};prefs().edit().putString(STORY,s).apply();pass(5,"Story persisted (${s.length} chars)")}
    private fun operateTarget(){if(!begin(6))return;val i=packageManager.getLaunchIntentForPackage(target);if(i==null){fail(6,"Target cannot be launched");return};i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP);UniversalAccessibilityService.targetPackage=target;startActivity(i);pass(6,"Target launch requested; waiting for Accessibility foreground proof");waitForTargetForeground(0)}
    private fun waitForTargetForeground(attempt:Int){if(gate.state(7)!=StageGate.State.READY)return;if(UniversalAccessibilityService.targetForeground){deepStudy();return};if(attempt>=20){fail(7,"Target did not become foreground in Accessibility service within 10 seconds");return};mainHandler.postDelayed({waitForTargetForeground(attempt+1)},500L)}
    private fun deepStudy(){if(!begin(7))return;if(!UniversalAccessibilityService.isEnabled){fail(7,"Accessibility service unavailable");return};val root=UniversalAccessibilityService.instance?.rootInActiveWindow;if(root==null){fail(7,"Target accessibility tree unavailable; target must be foreground");return};var nodes=0;var clickable=0;var editable=0;fun walk(n:AccessibilityNodeInfo?){if(n==null)return;nodes++;if(n.isClickable)clickable++;if(n.isEditable)editable++;for(i in 0 until n.childCount)walk(n.getChild(i))};walk(root);root.recycle();if(nodes<1){fail(7,"No accessibility nodes discovered");return};prefs().edit().putString("target_ui_map","nodes=$nodes;clickable=$clickable;editable=$editable").apply();pass(7,"Live UI map captured: nodes=$nodes clickable=$clickable editable=$editable")}
    private fun scenePlan(){if(!begin(8))return;val s=prefs().getString(STORY,"")?:"";if(s.isBlank()){fail(8,"Story missing");return};val parts=s.split(Regex("(?<=[.!?])\\s+")).filter{it.isNotBlank()}.take(30);val chunks=if(parts.isEmpty())listOf(s)else parts;val scenes=chunks.mapIndexed{idx,x->"SCENE_${idx+1}\nACTION=${x.trim()}\nBACKGROUND=scene-specific\nCHARACTER=consistent\nCLIP=recorded\n"}.joinToString("\n");prefs().edit().putString(SCENES,scenes).apply();pass(8,"Ordered scene plan created: ${chunks.size} scenes")}
    private fun buildPlan(){if(!begin(9))return;val scenes=prefs().getString(SCENES,"")?:"";if(scenes.isBlank()){fail(9,"Scene plan missing");return};val plan=scenes.lines().filter{it.startsWith("SCENE_")}.joinToString("\n"){it+" | VISUAL_PROMPT=cinematic_3D_cartoon_consistent_character | ACTION_PROMPT=execute_scene_action"};prefs().edit().putString(PLAN,plan).apply();pass(9,"Production prompts generated for every ordered scene")}
    private fun audioAndRecord(){if(!begin(10))return;val text=prefs().getString(STORY,"")?:"";if(text.isBlank()){fail(10,"Story missing for narration");return};if(tts==null){tts=TextToSpeech(this){if(it==TextToSpeech.SUCCESS)tts?.language=Locale.US};status.text="Stage 10 RUNNING • initializing voice engine";mainHandler.postDelayed({if(gate.state(10)==StageGate.State.RUNNING)audioAndRecordRetry(text,0)},500L);return};audioAndRecordRetry(text,0)}
    private fun audioAndRecordRetry(text:String,attempt:Int){val engine=tts;if(engine==null){if(attempt>=10){fail(10,"Text-to-speech engine is not initialized");return};mainHandler.postDelayed({audioAndRecordRetry(text,attempt+1)},500L);return};prefs().edit().remove(RECORDING).putLong(RECORDING_START,System.currentTimeMillis()/1000L).apply();val out=File(cacheDir,"narration_${sid}.wav");try{engine.language=Locale.US;engine.setOnUtteranceProgressListener(object:UtteranceProgressListener(){override fun onStart(utteranceId:String?){};override fun onDone(utteranceId:String?){runOnUiThread{if(gate.state(10)!=StageGate.State.RUNNING)return@runOnUiThread;if(!out.isFile||out.length()<100){fail(10,"TTS completion reported but narration file is unusable");return@runOnUiThread};prefs().edit().putString(AUDIO,out.absolutePath).apply();status.text="Stage 10 READY • voice generated • request screen recording";val m=getSystemService(MediaProjectionManager::class.java);capture.launch(m.createScreenCaptureIntent())}};override fun onError(utteranceId:String?){runOnUiThread{if(gate.state(10)==StageGate.State.RUNNING)fail(10,"Text-to-speech reported an error")}}});val result=engine.synthesizeToFile(text,Bundle(),out,"kunal_narration_${sid}");if(result!=TextToSpeech.SUCCESS)fail(10,"TTS synthesis request was rejected")}catch(e:Exception){fail(10,"Audio synthesis failed: ${e.javaClass.simpleName}")}}
    fun startRecordingFromBridge(){if(gate.state(10)==StageGate.State.READY)audioAndRecord()}
    fun stopRecordingFromBridge(){if(gate.state(10)!=StageGate.State.RUNNING)return;startService(Intent(this,ScreenCaptureService::class.java).setAction(ScreenCaptureService.STOP));waitForRecordingCompletion(0)}
    private fun waitForRecordingCompletion(attempt:Int){if(gate.state(10)!=StageGate.State.RUNNING)return;val uri=latestRecording();if(uri!=null){prefs().edit().putString(RECORDING,uri.toString()).apply();pass(10,"Screen recording finalized: $uri");return};if(attempt>=20){fail(10,"Recording stop completed but no new finalized MediaStore video was found");return};mainHandler.postDelayed({waitForRecordingCompletion(attempt+1)},500L)}
    private fun latestRecording():android.net.Uri?{prefs().getString(RECORDING,null)?.let{try{return android.net.Uri.parse(it)}catch(_:Exception){}};val since=prefs().getLong(RECORDING_START,0L);val c=contentResolver.query(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,arrayOf(MediaStore.Video.Media._ID),"${MediaStore.Video.Media.DISPLAY_NAME} LIKE ? AND ${MediaStore.Video.Media.DATE_ADDED} >= ?",arrayOf("KunalUniversalVideo_%",since.toString()),"${MediaStore.Video.Media.DATE_ADDED} DESC")?:return null;return c.use{if(it.moveToFirst())MediaStore.Video.Media.EXTERNAL_CONTENT_URI.buildUpon().appendPath(it.getString(0)).build()else null}}
    private fun assembleEdit(){if(!begin(11))return;val r=prefs().getString(RECORDING,"")?:"";val a=prefs().getString(AUDIO,"")?:"";if(r.isBlank()||a.isBlank()){fail(11,"Recording or narration missing");return};try{val out=muxVideoAudio(android.net.Uri.parse(r),File(a));prefs().edit().putString(FINAL,out.toString()).apply();pass(11,"Video/audio muxed and verified: $out")}catch(e:Exception){fail(11,"Assembly failed: ${e.javaClass.simpleName}")}}
    private fun muxVideoAudio(videoUri:android.net.Uri,audioFile:File):android.net.Uri{val ve=MediaExtractor();ve.setDataSource(this,videoUri,null);var vt=-1;for(i in 0 until ve.trackCount)if(ve.getTrackFormat(i).getString(MediaFormat.KEY_MIME)?.startsWith("video/")==true){vt=i;break};if(vt<0)throw IllegalStateException("video track missing");val af=MediaExtractor();af.setDataSource(audioFile.absolutePath);var at=-1;for(i in 0 until af.trackCount)if(af.getTrackFormat(i).getString(MediaFormat.KEY_MIME)?.startsWith("audio/")==true){at=i;break};if(at<0)throw IllegalStateException("audio track missing");val values=ContentValues().apply{put(MediaStore.Video.Media.DISPLAY_NAME,"KunalUniversalVideo_${sid}.mp4");put(MediaStore.Video.Media.MIME_TYPE,"video/mp4");if(android.os.Build.VERSION.SDK_INT>=29){put(MediaStore.Video.Media.RELATIVE_PATH,"Movies/KunalUniversalVideo");put(MediaStore.Video.Media.IS_PENDING,1)}};val uri=contentResolver.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,values)?:throw IllegalStateException("MediaStore insert failed");try{ve.selectTrack(vt);af.selectTrack(at);val pfd=contentResolver.openFileDescriptor(uri,"w")?:throw IllegalStateException("output descriptor missing");pfd.use{val mux=MediaMuxer(it.fileDescriptor,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);val vout=mux.addTrack(ve.getTrackFormat(vt));val aout=mux.addTrack(af.getTrackFormat(at));mux.start();val buf=java.nio.ByteBuffer.allocate(1024*1024);val info=MediaCodec.BufferInfo();while(true){val n=ve.readSampleData(buf,0);if(n<0)break;info.offset=0;info.size=n;info.presentationTimeUs=ve.sampleTime;info.flags=ve.sampleFlags;mux.writeSampleData(vout,buf,info);ve.advance()};while(true){val n=af.readSampleData(buf,0);if(n<0)break;info.offset=0;info.size=n;info.presentationTimeUs=af.sampleTime;info.flags=af.sampleFlags;mux.writeSampleData(aout,buf,info);af.advance()};mux.stop();mux.release()}};if(android.os.Build.VERSION.SDK_INT>=29)contentResolver.update(uri,ContentValues().apply{put(MediaStore.Video.Media.IS_PENDING,0)},null,null);ve.release();af.release();return uri}
    private fun verifyAndFix(){if(!begin(12))return;val u=prefs().getString(FINAL,"")?:"";if(u.isBlank()){fail(12,"Final media missing");return};val e=MediaExtractor();try{e.setDataSource(this,android.net.Uri.parse(u),null);var v=false;var a=false;for(i in 0 until e.trackCount){val m=e.getTrackFormat(i).getString(MediaFormat.KEY_MIME)?:(continue);if(m.startsWith("video/"))v=true;if(m.startsWith("audio/"))a=true};if(!v||!a)throw IllegalStateException("required tracks missing");pass(12,"Final media verified: playable video + audio tracks present")}catch(ex:Exception){fail(12,"Verification failed: ${ex.javaClass.simpleName}")}finally{e.release()}}
    private fun finalExport(){if(!begin(13))return;val u=prefs().getString(FINAL,"")?:"";if(u.isBlank()){fail(13,"Final media URI missing");return};pass(13,"Final gallery export ready: $u")}
    override fun onDestroy(){mainHandler.removeCallbacksAndMessages(null);tts?.shutdown();bridge?.stop();bridge=null;super.onDestroy()}
}
