package com.kunal.universalvideo
import android.app.Activity
import android.content.ContentValues
import android.content.Intent
import android.content.pm.PackageManager
import android.media.projection.MediaProjectionManager
import android.os.Bundle
import android.provider.MediaStore
import android.provider.Settings
import android.speech.tts.TextToSpeech
import android.view.Gravity
import android.widget.*
import androidx.activity.ComponentActivity
import androidx.activity.result.contract.ActivityResultContracts
import java.io.File
import java.util.Locale
import java.util.UUID

class MainActivity:ComponentActivity(){
 companion object{const val P="kuv";const val TARGET="target_package";const val SESSION="session_id";const val STORY="story";const val PLAN="plan";const val FP="fingerprint";const val SNAP="snapshot";const val AUDIO="audio";const val CHROMATOONS="bhootiyadreamstv.moboapp.chromatoons"}
 lateinit var gate:StageGate;lateinit var status:TextView;lateinit var story:EditText;lateinit var spinner:Spinner
 var bridge:LocalBridgeService?=null;var target="";var sid="";var tts:TextToSpeech?=null;var ttsReady=false;var apps:List<android.content.pm.ApplicationInfo> = emptyList()
 val capture=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==Activity.RESULT_OK&&r.data!=null){val i=Intent(this,ScreenCaptureService::class.java).setAction(ScreenCaptureService.START).putExtra(ScreenCaptureService.CODE,r.resultCode).putExtra(ScreenCaptureService.DATA,r.data);if(android.os.Build.VERSION.SDK_INT>=26)startForegroundService(i)else startService(i);status.text="Stage 10 RUNNING • fallback recording"}else status.text="Stage 10 FAIL • recording permission cancelled"}
 override fun onCreate(b:Bundle?){super.onCreate(b);gate=StageGate(this);val p=getSharedPreferences(P,0);sid=p.getString(SESSION,null)?:UUID.randomUUID().toString();p.edit().putString(SESSION,sid).apply();ui(p);tts=TextToSpeech(this){x->ttsReady=x==TextToSpeech.SUCCESS;if(ttsReady)tts?.language=Locale.US};bridge=LocalBridgeService(this,sid){m->runOnUiThread{status.text=m}};bridge?.start();stage1()}
 fun ui(p:android.content.SharedPreferences){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,20)};r.addView(TextView(this).apply{text="Kunal Universal Video";textSize=26f});status=TextView(this).apply{textSize=15f;setPadding(0,10,0,10)};r.addView(status);spinner=Spinner(this);r.addView(spinner);story=EditText(this).apply{hint="Stage 5 story";minLines=4;gravity=Gravity.TOP;setText(p.getString(STORY,""))};r.addView(story,LinearLayout.LayoutParams(-1,0,1f));val a=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};fun b(t:String,f:()->Unit)=Button(this).apply{text=t;setOnClickListener{f()};a.addView(this)};b("2 ENABLE ACCESSIBILITY"){startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))};b("2 CONNECT MOBILE"){s2()};b("3 SELECT TARGET"){s3()};b("4 STUDY TARGET UI"){s4()};b("5 SAVE STORY"){s5()};b("6 PLAN + AUDIO"){s6()};b("7 DEEP UI FINGERPRINT"){s7()};b("8 EXECUTABLE SCENE PLAN"){s8()};b("9 OPERATE TARGET"){s9()};b("10 RECORD / STOP"){s10()};b("11 VERIFY VIDEO"){s11()};b("12 FINAL GALLERY EXPORT"){s12()};b("REFRESH"){render()};r.addView(a);setContentView(r)}
 fun begin(i:Int)=if(gate.isUnlocked(i)){gate.begin(i);true}else{status.text="Stage $i LOCKED";false};fun pass(i:Int,e:String){gate.pass(i,e);status.text="Stage $i PASS • $e";render()};fun fail(i:Int,e:String){gate.fail(i,e);status.text="Stage $i FAIL • $e";render()};fun render(){val i=gate.currentStage();status.text="Stage $i • ${gate.state(i)} • Session ${sid.take(8)}"}
 fun stage1(){if(gate.state(1)!=StageGate.State.PASS){gate.resetForRepair(1);gate.begin(1);gate.pass(1,"MainActivity launched")};loadApps();render()}
 fun loadApps(){apps=packageManager.getInstalledApplications(PackageManager.ApplicationInfoFlags.of(0)).filter{it.packageName!=packageName}.sortedBy{packageManager.getApplicationLabel(it).toString().lowercase()};spinner.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,apps.map{"${packageManager.getApplicationLabel(it)}\n${it.packageName}"});val saved=getSharedPreferences(P,0).getString(TARGET,"")?:"";val pick=if(saved.isNotBlank())saved else CHROMATOONS;val n=apps.indexOfFirst{it.packageName==pick};if(n>=0){spinner.setSelection(n);target=pick}}
 fun s2(){if(!begin(2))return;if(!UniversalAccessibilityService.isEnabled){fail(2,"Accessibility service is OFF");return};if(target.isBlank()){fail(2,"Target not selected");return};UniversalAccessibilityService.targetPackage=target;bridge?.connect(target);pass(2,"Accessibility active + local session connected")}
 fun s3(){if(!gate.isUnlocked(2))return;val n=spinner.selectedItemPosition;if(n !in apps.indices){status.text="Select target";return};target=apps[n].packageName;getSharedPreferences(P,0).edit().putString(TARGET,target).apply();UniversalAccessibilityService.targetPackage=target;gate.resetForRepair(3);if(begin(3))pass(3,"Target=$target${if(target==CHROMATOONS)" (ChromaToons)" else ""}")}
 fun s4(){if(!begin(4))return;if(target.isBlank()){fail(4,"Target missing");return};val i=packageManager.getLaunchIntentForPackage(target)?:run{fail(4,"No launch intent");return};i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP);startActivity(i);if(!wait(3000){UniversalAccessibilityService.targetForeground}){fail(4,"Target foreground not observed");return};val x=UniversalAccessibilityService.snapshot();if(x.optInt("node_count")<1){fail(4,"No accessible target nodes");return};getSharedPreferences(P,0).edit().putString(SNAP,x.toString()).apply();pass(4,"UI study captured nodes=${x.optInt("node_count")}")}
 fun s5(){if(!begin(5))return;val s=story.text.toString().trim();if(s.length<10){fail(5,"Story too short");return};getSharedPreferences(P,0).edit().putString(STORY,s).apply();pass(5,"Story saved")}
 fun s6(){if(!begin(6))return;val s=getSharedPreferences(P,0).getString(STORY,"")?:"";if(s.isBlank()){fail(6,"Story missing");return};val ss=s.split(Regex("(?<=[.!?])\\s+")).filter{it.isNotBlank()}.ifEmpty{listOf(s)}.take(12);val a=org.json.JSONArray();ss.forEachIndexed{i,x->a.put(org.json.JSONObject().put("scene",i+1).put("story",x.trim()).put("actions",org.json.JSONArray().put("OPEN_TARGET").put("FIND_CHARACTER_CONTROL").put("FIND_BACKGROUND_CONTROL").put("RECORD_TARGET_OUTPUT")))};getSharedPreferences(P,0).edit().putString(PLAN,org.json.JSONObject().put("schema","kuv-scene-v2").put("target",CHROMATOONS).put("scenes",a).toString()).apply();if(!ttsReady){fail(6,"TTS not ready");return};val f=File(filesDir,"narration.wav");if(tts?.synthesizeToFile(s,Bundle(),f,"narration")!=TextToSpeech.SUCCESS||!wait(3000){f.exists()&&f.length()>0}){fail(6,"Narration audio file creation failed");return};getSharedPreferences(P,0).edit().putString(AUDIO,f.absolutePath).apply();pass(6,"Plan + prompts + real narration audio file created")}
 fun s7(){if(!begin(7))return;if(!UniversalAccessibilityService.isEnabled||!UniversalAccessibilityService.targetForeground){fail(7,"Accessibility/foreground missing");return};val x=UniversalAccessibilityService.fingerprint();if(x.optInt("node_count")<1){fail(7,"No UI nodes");return};getSharedPreferences(P,0).edit().putString(FP,x.toString()).apply();pass(7,"Deep fingerprint captured nodes=${x.optInt("node_count")}")}
 fun s8(){if(!begin(8))return;val p=getSharedPreferences(P,0).getString(PLAN,"")?:"";val f=getSharedPreferences(P,0).getString(FP,"")?:"";if(p.isBlank()||f.isBlank()){fail(8,"Plan/fingerprint missing");return};val n=org.json.JSONObject(p).optJSONArray("scenes")?.length()?:0;if(n<1){fail(8,"No scenes");return};pass(8,"Executable ${n}-scene plan validated")}
 fun s9(){if(!begin(9))return;if(!UniversalAccessibilityService.targetForeground){if(!UniversalAccessibilityService.launchPackage(target)||!wait(3000){UniversalAccessibilityService.targetForeground}){fail(9,"Target not foreground");return}};val before=UniversalAccessibilityService.snapshot();var used="";for(q in listOf("avatar","character","background","bg","sp","anim","ik")){if(UniversalAccessibilityService.click(q)){used=q;break}};if(used.isBlank()){fail(9,"No semantic target control exposed; visual/coordinate map required");return};val after=UniversalAccessibilityService.snapshot();if(after.toString()==before.toString()){fail(9,"Action had no observable effect");return};pass(9,"Real target UI action executed: $used")}
 fun s10(){if(!gate.isUnlocked(10)){status.text="Stage 10 LOCKED";return};if(gate.state(10)==StageGate.State.RUNNING){if(UniversalAccessibilityService.targetForeground)UniversalAccessibilityService.click("record") else startService(Intent(this,ScreenCaptureService::class.java).setAction(ScreenCaptureService.STOP));if(!wait(5000){latest()!=null}){fail(10,"No video output after stop");return};pass(10,"Recording produced video output");return};if(!begin(10))return;if(UniversalAccessibilityService.targetForeground&&UniversalAccessibilityService.click("record")){status.text="Stage 10 RUNNING • target record started • press again to stop";return};capture.launch(getSystemService(MediaProjectionManager::class.java).createScreenCaptureIntent())}
 fun s11(){if(!begin(11))return;val u=latest()?:run{fail(11,"No video");return};val m=android.media.MediaMetadataRetriever();try{m.setDataSource(this,u);val d=m.extractMetadata(android.media.MediaMetadataRetriever.METADATA_KEY_DURATION)?.toLongOrNull()?:0;val w=m.extractMetadata(android.media.MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH)?.toIntOrNull()?:0;val h=m.extractMetadata(android.media.MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT)?.toIntOrNull()?:0;if(d<500||w<1||h<1){fail(11,"Invalid video ${d}ms ${w}x${h}");return};pass(11,"Decoded video ${d}ms ${w}x${h}")}catch(e:Exception){fail(11,"Decode failed ${e.javaClass.simpleName}")}finally{m.release()}}
 fun s12(){if(!begin(12))return;val src=latest()?:run{fail(12,"Verified video missing");return};val name="KUV_FINAL_${System.currentTimeMillis()}.mp4";val v=ContentValues().apply{put(MediaStore.Video.Media.DISPLAY_NAME,name);put(MediaStore.Video.Media.MIME_TYPE,"video/mp4");if(android.os.Build.VERSION.SDK_INT>=29){put(MediaStore.Video.Media.RELATIVE_PATH,"Movies/KunalUniversalVideo");put(MediaStore.Video.Media.IS_PENDING,1)}};val dst=contentResolver.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,v)?:run{fail(12,"Gallery destination failed");return};try{contentResolver.openInputStream(src).use{a->contentResolver.openOutputStream(dst).use{b->if(a==null||b==null)throw IllegalStateException();a.copyTo(b)}};if(android.os.Build.VERSION.SDK_INT>=29)contentResolver.update(dst,ContentValues().apply{put(MediaStore.Video.Media.IS_PENDING,0)},null,null);pass(12,"Final MP4 copied and verified in Gallery: $name")}catch(e:Exception){contentResolver.delete(dst,null,null);fail(12,"Export failed ${e.javaClass.simpleName}")}}
 fun latest():android.net.Uri?{val u=MediaStore.Video.Media.EXTERNAL_CONTENT_URI;return contentResolver.query(u,arrayOf(MediaStore.Video.Media._ID),"${MediaStore.Video.Media.DISPLAY_NAME} LIKE ?",arrayOf("KunalUniversalVideo_%"),"${MediaStore.Video.Media.DATE_ADDED} DESC")?.use{if(it.moveToFirst())android.content.ContentUris.withAppendedId(u,it.getLong(0))else null}}
 fun wait(ms:Long,p:()->Boolean):Boolean{val e=System.currentTimeMillis()+ms;while(System.currentTimeMillis()<e){if(p())return true;Thread.sleep(100)};return p()}
 override fun onResume(){super.onResume();if(::gate.isInitialized)render()};override fun onDestroy(){tts?.shutdown();bridge?.stop();super.onDestroy()};fun startRecordingFromBridge(){if(gate.isUnlocked(10))s10()};fun stopRecordingFromBridge(){startService(Intent(this,ScreenCaptureService::class.java).setAction(ScreenCaptureService.STOP))}
}
