#!/usr/bin/env python3
"""Production source wiring for the real Stage-2 connection path.

The production builder historically reconstructed a small demo MainActivity after
extracting the authoritative project. That could silently discard the locked 1..13
StageGate implementation. This narrow, idempotent patch makes the builder use the
checked-in activity_fixed.kt + stage_gate.kt as the authoritative UI/gate while
retaining the real controller/accessibility/media components generated by V3.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
builder = ROOT / "pro_repair_v3.py"
activity = ROOT / "activity_fixed.kt"
stage_gate = ROOT / "stage_gate.kt"
if not builder.is_file():
    raise SystemExit("PROD_WIRING: pro_repair_v3.py missing")
if not activity.is_file():
    raise SystemExit("PROD_WIRING: activity_fixed.kt missing")
if not stage_gate.is_file():
    raise SystemExit("PROD_WIRING: stage_gate.kt missing")

s = builder.read_text(encoding="utf-8")
a = activity.read_text(encoding="utf-8").strip()
g = stage_gate.read_text(encoding="utf-8").strip()

# Replace only the embedded ACTIVITY literal. This leaves the rest of the V3
# reconstruction machinery intact and is safe to run repeatedly.
pat = re.compile(r"ACTIVITY=r'''[\\s\\S]*?'''\\nMANIFEST=", re.M)
replacement = "ACTIVITY=r'''" + a + "'''\nMANIFEST="
s2, n = pat.subn(replacement, s, count=1)
if n != 1:
    raise SystemExit("PROD_WIRING: embedded ACTIVITY literal not found")
s = s2

# Add an embedded StageGate literal once.
if "STAGE_GATE=r'''" not in s:
    marker = "MANIFEST=r'''"
    idx = s.find(marker)
    if idx < 0:
        raise SystemExit("PROD_WIRING: MANIFEST marker not found")
    s = s[:idx] + "STAGE_GATE=r'''" + g + "'''\n" + s[idx:]

# Ensure reconstruct() writes StageGate.kt and the authoritative activity path.
needle = 'for n,d in [("ControllerProtocol.kt",PROTOCOL),("LocalBridgeService.kt",BRIDGE),("UniversalAccessibilityService.kt",ACCESS),("ScreenCaptureService.kt",CAPTURE),("MainActivity.kt",ACTIVITY)]:write(java/n,d)'
replacement_write = 'for n,d in [("ControllerProtocol.kt",PROTOCOL),("LocalBridgeService.kt",BRIDGE),("UniversalAccessibilityService.kt",ACCESS),("ScreenCaptureService.kt",CAPTURE),("MainActivity.kt",ACTIVITY),("StageGate.kt",STAGE_GATE)]:write(java/n,d)'
if needle in s:
    s = s.replace(needle, replacement_write, 1)
elif '"StageGate.kt",STAGE_GATE' not in s:
    raise SystemExit("PROD_WIRING: reconstruct source-write block not found")

builder.write_text(s, encoding="utf-8")
print("PROD_WIRING=PASS")
